### ISSUE TITLE
Unable to set up local project due to missing Electron dependency

### ISSUE THREAD

**Issue by a2** [chrismaltby/gb-studio#1202]
**Describe the bug**
Cloned and tried to set up project locally on Apple Silicon Mac. Yarn install complains that Electron 8.5.5 does not exist. I see that Electron 8.x.y is EOL [on this page](https://www.electronjs.org/releases/stable?version=8#end-of-support-for-8xy-855), though. Maybe it's worth upgrading that dependency but I don't know what that affects.

**To Reproduce**
1. `git clone https://github.com/chrismaltby/gb-studio.git`
2. `cd gb-studio`
3. `yarn install`

**Expected behavior**
I should be able to set up the project locally by following the steps in the readme.

**Platform:**
 - OS: macOS 12.5.1 on Apple Silicon Mac
 - App version: 940c16a0b15e0462413946b683efe7901ce2d523 (latest develop branch as of this writing)

**Additional context**

<details>
<summary>Error Log</summary>

```
# This file contains the result of Yarn building a package (electron@npm:8.5.5)
# Script name: postinstall

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v8.5.5/electron-v8.5.5-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/a2/Desktop/gb-studio/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:513:28)
    at module.exports (/Users/a2/Desktop/gb-studio/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/a2/Desktop/gb-studio/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/Users/a2/Desktop/gb-studio/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:534:22) {
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v8.5.5/electron-v8.5.5-darwin-arm64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v8.5.5/electron-v8.5.5-darwin-arm64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v8.5.5/electron-v8.5.5-darwin-arm64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v8.5.5/electron-v8.5.5-darwin-arm64.zip',
    href: 'https://github.com/electron/electron/releases/download/v8.5.5/electron-v8.5.5-darwin-arm64.zip',
    retry: {
      retries: [Function (anonymous)],
      methods: Set(6) { 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' },
      statusCodes: Set(7) { 408, 413, 429, 500, 502, 503, 504 },
      errorCodes: Set(8) {
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      }
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  },
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'GitHub.com',
    date: 'Mon, 05 Sep 2022 16:54:15 GMT',
    'content-type': 'text/plain; charset=utf-8',
    vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
    'permissions-policy': 'interest-cohort=()',
    'cache-control': 'no-cache',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'x-frame-options': 'deny',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '0',
    'referrer-policy': 'no-referrer-when-downgrade',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    'content-encoding': 'gzip',
    'content-length': '29',
    'x-github-request-id': 'D2D6:0EB6:59280F:9E5513:631629B7',
    connection: 'close'
  },
  body: undefined
}

Node.js v18.8.0
```
</details>

**Comment by chrismaltby** [comment]
Ah that's interesting to know it's now EOL. I've got a local branch where I had tried migrating to Electron 15, but it needed quite a lot of changes to make everything work. Currently trying to finish up a 3.1.0 release and I was going to pick this branch back up (and probably move to Electron 20 now as it's the latest stable) once we've got the next release out

**Comment by a2** [comment]
Sounds good. I can still use the pre-compiled releases but I thought I would look at the new shiny. Thanks!
