### ISSUE TITLE
Can't start from source on Ubuntu 20.04

### ISSUE THREAD

**Issue by ianling** [chrismaltby/gb-studio#439]
**Describe the bug**
After cloning the repo, running `yarn`, and running `npm start`, an error occurs that prevents GB-Studio from running.

**To Reproduce**
1. Clone repo
2. Enter gb-studio directory, run `yarn`
3. Run `npm start`

**Expected behavior**
The program starts successfully

**Screenshots**

**Platform (please complete the following information):**
 - OS: Ubuntu 20.04 x86-64
 - App version 1.2.1 (latest git source)

**Additional context**
Terminal output:

```
iling:~$ git clone https://github.com/chrismaltby/gb-studio.git
Cloning into 'gb-studio'...
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 25358 (delta 80), reused 97 (delta 48), pack-reused 25194
Receiving objects: 100% (25358/25358), 46.35 MiB | 9.71 MiB/s, done.
Resolving deltas: 100% (12734/12734), done.
iling:~$ cd gb-studio/
iling:~/gb-studio$ yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.1: The platform "linux" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info appdmg@0.4.5: The platform "linux" is incompatible with this module.
info "appdmg@0.4.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info macos-alias@0.2.11: The platform "linux" is incompatible with this module.
info "macos-alias@0.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-select-async-paginate@0.3.10" has unmet peer dependency "@types/react-select@^3.0.0".
warning " > eslint-config-react-app@4.0.1" has unmet peer dependency "@typescript-eslint/eslint-plugin@1.x".
warning " > eslint-config-react-app@4.0.1" has unmet peer dependency "@typescript-eslint/parser@1.x".
warning " > eslint-config-react-app@4.0.1" has incorrect peer dependency "babel-eslint@10.x".
[4/4] Building fresh packages...
Done in 23.50s.
iling:~/gb-studio$ npm start

> gb-studio@1.2.1 start /home/iling/gb-studio
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
No language pack for user setting, falling back to en
Add a language pack by making the file src/lang/en-US.json
(node:16387) UnhandledPromiseRejectionWarning: Error: Exited with code 9
    at ChildProcess.<anonymous> (/home/iling/gb-studio/node_modules/cross-unzip/index.js:38:21)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
(node:16387) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16387) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
<... hangs here indefinitely ...>
```

**Comment by cubicstyle** [comment]
See here. You should fix it like this:
https://github.com/electron/fiddle/issues/454
https://github.com/electron/fiddle/pull/455/files/40f9164044a4464cc54c4a815d7c1a78a5b04066

So I want to request electron-devtools-installer version to upgrade.

diff --git "a/package.json" "b/package.json"
index a37370b7..7bc6627d 100644
--- "a/package.json"
+++ "b/package.json"
@@ -42,7 +42,7 @@
     "classnames": "^2.2.5",
     "deepmerge": "^3.1.0",
     "electron-compile": "^6.4.4",
-    "electron-devtools-installer": "^2.1.0",
+    "electron-devtools-installer": "^3.1.1",
     "electron-is": "^3.0.0",
     "electron-settings": "^3.2.0",
     "electron-squirrel-startup": "^1.0.0",

**Comment by skayth1997** [comment]
same error
