### ISSUE TITLE
Can't compile on Manjaro Linux

### ISSUE THREAD

**Issue by LiamDawe** [chrismaltby/gb-studio#479]
Hi, I'm trying to compile the 2.0 Beta on Manjaro Linux, using the instructions on the GitHub page.

It gets as far as this:

> ✖ Compiling Main Process Code
> 
> An unhandled error has occurred inside Forge:
> Command failed: git describe --always
> fatal: not a git repository (or any of the parent directories): .git
> 
> Error: Command failed: git describe --always
> fatal: not a git repository (or any of the parent directories): .git
> 
>     at checkExecSyncError (child_process.js:616:11)
>     at execSync (child_process.js:652:15)
>     at module.exports (/home/liam/Downloads/gb-studio-2beta/node_modules/git-revision-webpack-plugin/lib/helpers/run-git-command.js:25:34)
>     at GitRevisionPlugin.version (/home/liam/Downloads/gb-studio-2beta/node_modules/git-revision-webpack-plugin/lib/index.js:65:10)
>     at Object.<anonymous> (/home/liam/Downloads/gb-studio-2beta/webpack.plugins.js:12:49)
>     at Module._compile (internal/modules/cjs/loader.js:1251:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
>     at Module.load (internal/modules/cjs/loader.js:1100:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:962:14)
>     at Module.require (internal/modules/cjs/loader.js:1140:19)
>     at require (internal/modules/cjs/helpers.js:75:18)
>     at Object.<anonymous> (/home/liam/Downloads/gb-studio-2beta/webpack.main.config.js:1:17)
>     at Module._compile (internal/modules/cjs/loader.js:1251:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
>     at Module.load (internal/modules/cjs/loader.js:1100:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:962:14)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! gb-studio@2.0.0-beta1 start: `electron-forge start`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the gb-studio@2.0.0-beta1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/liam/.npm/_logs/2020-08-26T11_09_24_450Z-debug.log

Here's the log file: https://pastebin.com/Lgzrh6TM

**Comment by patrickmollohan** [comment]
Ran into this as well yesterday after downloading the .zip file.
To fix, use git to clone the repository:
git clone -b v2beta https://github.com/chrismaltby/gb-studio.git
