### ISSUE TITLE
Unable to start v2 beta

### ISSUE THREAD

**Issue by hazelnot** [chrismaltby/gb-studio#770]
**Describe the bug**
Unable to start the v2 beta.

**To Reproduce**
1. yarn
2. npm start
3. 
```
$ npm start

> gb-studio@1.2.2 start
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
No language pack for user setting, falling back to en
Add a language pack by making the file src/lang/en-US.json
(node:46330) UnhandledPromiseRejectionWarning: Error: Exited with code 9
    at ChildProcess.<anonymous> (/home/hazelnot/git/gb-studio/node_modules/cross-unzip/index.js:38:21)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
(node:46330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:46330) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
4. Nothing happens, no window, no nothing

**Expected behavior**
The thing starting

**Platform (please complete the following information):**
 - OS: Arch Linux
 - App version: 2.0 Beta

**Comment by pau-tomas** [comment]
Seems like you're trying to compile the "develop" branch (1.2.2) and not "v2beta".

**Comment by hazelnot** [comment]
...wow I'm a dumbass

**Comment by hazelnot** [comment]
Ok yeah wow I compiled the right branch and it works now sorry and thanks
