### ISSUE TITLE
Install on raspberry

### ISSUE THREAD

**Issue by jackygoule** [chrismaltby/gb-studio#815]
Hello i want to install gb-studio onn my raspberry pi4 but i never reach to install or run from source.
Is it possible to make a tutorial ?
i try and after a long time when "npm start"

> gb-studio@1.2.2 start
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
(node:2555) UnhandledPromiseRejectionWarning: Error: Exited with code 9
    at ChildProcess.<anonymous> (/home/pi/gb-studio/node_modules/cross-unzip/index.js:38:21)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
(node:2555) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2555) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

i use raspberry os.
Thanks

**Comment by sharkeylaser** [comment]
GB Studio 1 is not ARM-compatible. There's a pull request to add ARM compatibility for GBS 2 but it doesn't seem @chrismaltby has any interest in ever accepting it.

**Comment by jackygoule** [comment]
After update node and install libgconf-2-4
I have new error
` gb-studio@1.2.2 start
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
App threw an error during load
TypeError: (0 , _electronCompile.addBypassChecker) is not a function
    at Object.<anonymous> (/home/pi/gb-studio/src/index.js:57:39)
    at Module._compile (module.js:541:32)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pi/gb-studio/node_modules/electron-compile/lib/require-hook.js:36:14)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at init (/home/pi/gb-studio/node_modules/electron-compile/lib/config-parser.js:390:16)
    at main (/home/pi/gb-studio/node_modules/electron-prebuilt-compile/lib/es6-init.js:38:29)
    at Object.<anonymous> (/home/pi/gb-studio/node_modules/electron-prebuilt-compile/lib/es6-init.js:41:1)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: (0 , _electronCompile.addBypassChecker) is not a function
    at Object.<anonymous> (/home/pi/gb-studio/src/index.js:57:39)
    at Module._compile (module.js:541:32)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pi/gb-studio/node_modules/electron-compile/lib/require-hook.js:36:14)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at init (/home/pi/gb-studio/node_modules/electron-compile/lib/config-parser.js:390:16)
    at main (/home/pi/gb-studio/node_modules/electron-prebuilt-compile/lib/es6-init.js:38:29)
    at Object.<anonymous> (/home/pi/gb-studio/node_modules/electron-prebuilt-compile/lib/es6-init.js:41:1)
^C
`
Thanks for your help

ps:i am on pi4 and use raspberry pi os

**Comment by jackygoule** [comment]
I remove my clone of gb-studio and restart install.
when i run yarn:
yarn install v1.22.15
warning ../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.1: The platform "linux" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info appdmg@0.4.5: The platform "linux" is incompatible with this module.
info "appdmg@0.4.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info macos-alias@0.2.11: The platform "linux" is incompatible with this module.
info "macos-alias@0.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-select-async-paginate@0.3.10" has unmet peer dependency "@types/react-select@^3.0.0".
warning " > eslint-config-react-app@4.0.1" has unmet peer dependency "@typescript-eslint/eslint-plugin@1.x".
warning " > eslint-config-react-app@4.0.1" has unmet peer dependency "@typescript-eslint/parser@1.x".
warning " > eslint-config-react-app@4.0.1" has incorrect peer dependency "babel-eslint@10.x".
[4/4] Building fresh packages...
Done in 63.13s.


and when i run npm start 
 gb-studio@1.2.2 start /home/pi/gb-studio
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
(node:2098) UnhandledPromiseRejectionWarning: Error: Exited with code 9
    at ChildProcess.<anonymous> (/home/pi/gb-studio/node_modules/cross-unzip/index.js:38:21)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
(node:2098) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2098) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ReptiIe** [comment]
Sorry for necroposting people, but anyone who is involved in this or interested,
seems like GBS made a small step forward regarding RPI versions.

A whole new active topic is here:
https://github.com/chrismaltby/gb-studio/issues/1406

And test files are here:
https://github.com/chrismaltby/gb-studio/actions/runs/13006873084/job/36282779532

I believe this issue (although it is not solved) can be closed,
since in the active topic you have all you need to know about it.
