### ISSUE TITLE
GBStudio gives me an error saving music

### ISSUE THREAD

**Issue by bigjawed** [chrismaltby/gb-studio#872]
**Describe the bug**
When I try to save music, in some instances it will give me an error (HUGETracker)

**To Reproduce**
Go to music editor
Add some music notes
Try to save
Then it will give you an error

**Expected behavior**
Error: EPERM: operation not permitted, rename 'C:/Users/(name)/Google Drive/bit/Revision 3 (Glitchy Ammo)/assets/music/song_template 1.uge.new' -> 'C:/Users/(name)/Google Drive/bit/Revision 3 (Glitchy Ammo)/assets/music/song_template 1.uge'
at Object.renameSync (fs.js:643:3)
at file:///C:/Users/(name)/AppData/Local/gb_studio/app-3.0.0/resources/app.asar/.webpack/renderer/main_window/index.js:41851:18
at file:///C:/Users/(name)/AppData/Local/gb_studio/app-3.0.0/resources/app.asar/.webpack/renderer/main_window/index.js:41796:70
at file:///C:/Users/(name)/AppData/Local/gb_studio/app-3.0.0/resources/app.asar/.webpack/renderer/main_window/index.js:14505:14
at FSReqCallback.oncomplete (fs.js:146:23)

**Screenshots**

**Platform**
 - OS: Windows 10
 - App version 3.0.0

**Comment by ReptiIe** [comment]
I will wrote here as well - this hugetracker has some problems, doesn't work (as it should).
Example: SAVE tool button - doesn'y work.
To save a music you need to choose a new track (music), so there will be some window asking if you want to save your progress.

Platform:
* OS: Windows 10 Pro (64)
* App version 3.0.0

**Comment by pau-tomas** [comment]
Please confirm if this is still happening with version 3.0.1 and close the issue if it's been resolved. Thanks!

**Comment by bigjawed** [comment]
> Please confirm if this is still happening with version 3.0.1 and close the issue if it's been resolved. Thanks!

Can confirm, it works now.

**Comment by ReptiIe** [comment]
Seems that 3.0.1fix few problems (save button works fine thank you!), but there are still problems with the "music editor".
As for now I won't post a new issue, only will put here few things as a suggestion @pau-tomas 

Example:
Tempo. Usually it is set to "6", if you will change it (example 20), it will not do anything.
You have to SAVE the song, pick different one, and get back to your song.
- THIS way TEMPO will work.
Seems like problem with "song refreshing" or something.


Other suggestions (if no one thought about them yet):
1) Is it possible to make the [+] new music to have some sort of a window/wizard or something that will ask the "name of the song" and it will create a file like that? So users do not need to go to project folder, and rename the sample song template all the time :D
It doesn't need to be a window/wizard - but it would be nice for the user to be able to change the file name from the GBS, and not bother to go to the project folders for renaming the samples each time.

2) if there is [+] for making a new music, add [-] for deleting a music, maybe COPY/PASTE would also be nice

3) tool bar - missing stuff like, for example: 
- STOP; it will stop playing the song, and it will go back to start (as in any music player it works) 
- how about COPY,PASTE,DELETE menu for the patterns (and other stuff as well... em SONGS)?
